### ISSUE TITLE
deprecation

### ISSUE THREAD

**Issue by lxregistry** [tattali/MobileDetectBundle#17]
Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "MobileDetectBundle\DependencyInjection\MobileDetectExtension" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by tattali** [comment]
I will be happy to merge your PR. Thanks!
